server:
  port: 6677

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0

#zuul:
#  routes:
#    item-service:
#      path: /item-service/**
#      url: http://127.0.0.1:8891

zuul:
  routes:
    item-service:
      path: /item-service/**
#      url: http://127.0.0.1:8891
      serviceId: item-service
    order-service:
      path: /order-service/**
      serviceId: order-service

eureka:
  client:
    registerWithEureka: true # 是否将自己注册到 Eureka 服务中，本身就是服务所以无需注册
    fetchRegistry: true # 是否从 Eureka 中获取注册信息
    serviceUrl: # Eureka 客户端与 Eureka 服务端进行交互的地址
      defaultZone: http://test:test@127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true # 将自己的 IP 地址注册到 Eureka 服务中
